"""28+ 中国主要旅游城市种子数据。"""

SEED_DESTINATIONS = [
    {
        "id": "beijing",
        "name": "Beijing",
        "name_cn": "北京",
        "description": "China's sprawling capital, blending ancient imperial grandeur with cutting-edge modernity. Home to the Forbidden City, Great Wall, and world-class cuisine.",
        "image_url": "/images/destinations/beijing.jpg",
        "tags": ["history", "culture", "food"],
        "must_see": [
            {"name": "Forbidden City", "description": "The imperial palace complex from Ming to Qing dynasty, 980 buildings spread over 72 hectares.", "image_url": "/images/beijing/forbidden_city.jpg"},
            {"name": "Great Wall (Mutianyu)", "description": "One of the best-preserved sections, less crowded with stunning mountain views.", "image_url": "/images/beijing/great_wall.jpg"},
            {"name": "Temple of Heaven", "description": "A masterpiece of Chinese architecture where emperors prayed for good harvests.", "image_url": "/images/beijing/temple_of_heaven.jpg"},
        ],
        "must_eat": [
            {"name": "Peking Duck", "description": "Crispy, lacquered duck carved tableside, wrapped in thin pancakes with hoisin sauce.", "image_url": "/images/beijing/peking_duck.jpg"},
            {"name": "Zha Jiang Mian", "description": "Beijing-style noodles with thick fermented soybean paste and pork.", "image_url": "/images/beijing/zhajiangmian.jpg"},
            {"name": "Lamb Hot Pot", "description": "Traditional Mongolian-style hot pot, perfect for cold Beijing winters.", "image_url": "/images/beijing/hotpot.jpg"},
        ],
        "stay_tips": "Stay near Dongcheng district (Wangfujing/Gulou) for easy access to Forbidden City and hutongs. Wangfujing and Qianmen are tourist-friendly areas.",
        "best_days": 4,
        "budget_range": "$$$",
        "latitude": 39.9042,
        "longitude": 116.4074,
    },
    {
        "id": "shanghai",
        "name": "Shanghai",
        "name_cn": "上海",
        "description": "China's most cosmopolitan city — a dazzling fusion of futuristic skyscrapers, colonial-era architecture, and vibrant nightlife.",
        "image_url": "/images/destinations/shanghai.jpg",
        "tags": ["modern", "food", "shopping"],
        "must_see": [
            {"name": "The Bund", "description": "Iconic waterfront promenade lined with colonial buildings, facing Pudong's futuristic skyline.", "image_url": "/images/shanghai/bund.jpg"},
            {"name": "Shanghai Tower", "description": "China's tallest building at 632m, with breathtaking 360° observation deck.", "image_url": "/images/shanghai/tower.jpg"},
            {"name": "Yu Garden", "description": "A classical Ming Dynasty garden with intricate pavilions, rockeries, and koi ponds.", "image_url": "/images/shanghai/yu_garden.jpg"},
        ],
        "must_eat": [
            {"name": "Xiaolongbao (Soup Dumplings)", "description": "Delicate steamed dumplings filled with pork and hot soup.", "image_url": "/images/shanghai/xiaolongbao.jpg"},
            {"name": "Shengjianbao", "description": "Pan-fried pork buns with crispy bottom and juicy filling.", "image_url": "/images/shanghai/shengjian.jpg"},
            {"name": "Shanghai-style Braised Pork", "description": "Hongshao rou — caramelized pork belly braised in soy sauce and rock sugar.", "image_url": "/images/shanghai/braised_pork.jpg"},
        ],
        "stay_tips": "The Bund area or French Concession (Xintiandi) offer the best experiences. Pudong is modern but less charming for walking. Metro is excellent.",
        "best_days": 3,
        "budget_range": "$$$",
        "latitude": 31.2304,
        "longitude": 121.4737,
    },
    {
        "id": "guangzhou",
        "name": "Guangzhou",
        "name_cn": "广州",
        "description": "A bustling southern metropolis known for its Cantonese cuisine, colonial architecture, and role as a major trade hub.",
        "image_url": "/images/destinations/guangzhou.jpg",
        "tags": ["food", "culture", "shopping"],
        "must_see": [
            {"name": "Canton Tower", "description": "600m-tall tower with stunning city views and the world's highest open-air observation deck.", "image_url": "/images/guangzhou/canton_tower.jpg"},
            {"name": "Shamian Island", "description": "Colonial-era island with tree-lined avenues and European architecture.", "image_url": "/images/guangzhou/shamian.jpg"},
            {"name": "Chen Clan Ancestral Hall", "description": "A masterpiece of traditional Lingnan architecture, now a folk art museum.", "image_url": "/images/guangzhou/chen_clan.jpg"},
        ],
        "must_eat": [
            {"name": "Dim Sum", "description": "Cantonese dim sum is an art form — har gow (shrimp dumplings), siu mai, and char siu bao are must-tries.", "image_url": "/images/guangzhou/dimsum.jpg"},
            {"name": "Wonton Noodles", "description": "Thin egg noodles in shrimp broth with wontons filled with pork and shrimp.", "image_url": "/images/guangzhou/wonton.jpg"},
            {"name": "White Cut Chicken", "description": "Poached chicken served with ginger-scallion oil — simple yet sublime.", "image_url": "/images/guangzhou/chicken.jpg"},
        ],
        "stay_tips": "Stay near Tianhe CBD for modern convenience, or Liwan district for traditional Cantonese atmosphere. The metro is extensive and English-friendly.",
        "best_days": 3,
        "budget_range": "$$",
        "latitude": 23.1291,
        "longitude": 113.2644,
    },
    {
        "id": "shenzhen",
        "name": "Shenzhen",
        "name_cn": "深圳",
        "description": "China's Silicon Valley — a hyper-modern city that grew from a fishing village to a tech powerhouse in just four decades.",
        "image_url": "/images/destinations/shenzhen.jpg",
        "tags": ["modern", "shopping", "tech"],
        "must_see": [
            {"name": "OCT Loft", "description": "Creative arts district with galleries, cafes, and boutiques in revitalized factory buildings.", "image_url": "/images/shenzhen/oct_loft.jpg"},
            {"name": "Window of the World", "description": "Theme park with miniature replicas of world-famous landmarks.", "image_url": "/images/shenzhen/window_world.jpg"},
            {"name": "Dameisha Beach", "description": "Shenzhen's best city beach with golden sand and mountain backdrop.", "image_url": "/images/shenzhen/dameisha.jpg"},
        ],
        "must_eat": [
            {"name": "Seafood", "description": "Fresh seafood from the South China Sea — particularly at Shekou seafood street.", "image_url": "/images/shenzhen/seafood.jpg"},
            {"name": "Chaoshan Beef Hotpot", "description": "Thinly sliced premium beef cooked in clear broth, served with dipping sauces.", "image_url": "/images/shenzhen/beef_hotpot.jpg"},
            {"name": "Guangdong Roast Goose", "description": "Crispy-skinned roast goose, a Cantonese specialty done exceptionally well here.", "image_url": "/images/shenzhen/roast_goose.jpg"},
        ],
        "stay_tips": "Nanshan district (near OCT Loft) and Futian (near the CBD) are best for visitors. The metro is modern and easy to navigate.",
        "best_days": 2,
        "budget_range": "$$$",
        "latitude": 22.5431,
        "longitude": 114.0579,
    },
    {
        "id": "chengdu",
        "name": "Chengdu",
        "name_cn": "成都",
        "description": "The capital of Sichuan province — a laid-back city famous for pandas, fiery cuisine, and teahouse culture.",
        "image_url": "/images/destinations/chengdu.jpg",
        "tags": ["food", "nature", "culture"],
        "must_see": [
            {"name": "Giant Panda Breeding Research Base", "description": "See giant pandas up close in a natural habitat setting — the best place in the world for panda viewing.", "image_url": "/images/chengdu/panda.jpg"},
            {"name": "Jinli Ancient Street", "description": "A restored Qing Dynasty street with traditional architecture, snacks, and handicrafts.", "image_url": "/images/chengdu/jinli.jpg"},
            {"name": "Leshan Giant Buddha", "description": "A 71m-tall stone Buddha carved into a cliff face, a UNESCO World Heritage site.", "image_url": "/images/chengdu/leshan.jpg"},
        ],
        "must_eat": [
            {"name": "Hot Pot (Sichuan Style)", "description": "Fiery, numbing Sichuan peppercorn broth with a dizzying array of dipping ingredients.", "image_url": "/images/chengdu/hotpot.jpg"},
            {"name": "Mapo Tofu", "description": "Silken tofu in a fiery sauce of doubanjiang (fermented bean paste) and Sichuan pepper.", "image_url": "/images/chengdu/mapo_tofu.jpg"},
            {"name": "Kung Pao Chicken", "description": "The authentic version — diced chicken with peanuts, dried chilies, and Sichuan pepper.", "image_url": "/images/chengdu/kungpao.jpg"},
        ],
        "stay_tips": "Stay near Jinli or Taikoo Li for the best atmosphere. Chengdu is very walkable and has an excellent metro system.",
        "best_days": 3,
        "budget_range": "$$",
        "latitude": 30.5728,
        "longitude": 104.0668,
    },
    {
        "id": "xian",
        "name": "Xi'an",
        "name_cn": "西安",
        "description": "One of China's ancient capitals, home to the Terracotta Army and a living museum of Chinese civilization.",
        "image_url": "/images/destinations/xian.jpg",
        "tags": ["history", "culture", "food"],
        "must_see": [
            {"name": "Terracotta Army", "description": "Thousands of life-sized clay warriors guarding Emperor Qin's tomb — one of the world's greatest archaeological discoveries.", "image_url": "/images/xian/terracotta.jpg"},
            {"name": "Ancient City Wall", "description": "One of the best-preserved city walls in China, rent a bike and cycle the full 14km perimeter.", "image_url": "/images/xian/city_wall.jpg"},
            {"name": "Muslim Quarter", "description": "A vibrant maze of streets with incredible street food, mosques, and bazaar shopping.", "image_url": "/images/xian/muslim_quarter.jpg"},
        ],
        "must_eat": [
            {"name": "Biang Biang Noodles", "description": "Wide, hand-pulled noodles served with chili oil, garlic, and your choice of toppings.", "image_url": "/images/xian/biang_biang.jpg"},
            {"name": "Yangrou Paomo", "description": "Crumbled flatbread in rich lamb broth — Xi'an's most iconic dish.", "image_url": "/images/xian/paomo.jpg"},
            {"name": "Cold Noodles (Liangpi)", "description": "Chilled rice noodles with chili oil and vinegar — a perfect summer snack.", "image_url": "/images/xian/liangpi.jpg"},
        ],
        "stay_tips": "Stay within the city wall (Bell Tower area) for easy access to the main attractions. The Muslim Quarter is a great base for food lovers.",
        "best_days": 3,
        "budget_range": "$$",
        "latitude": 34.3416,
        "longitude": 108.9398,
    },
    {
        "id": "guilin",
        "name": "Guilin",
        "name_cn": "桂林",
        "description": "Famous for its ethereal karst mountain landscapes and Li River scenery — the quintessential Chinese landscape painting come to life.",
        "image_url": "/images/destinations/guilin.jpg",
        "tags": ["nature", "photography", "culture"],
        "must_see": [
            {"name": "Li River Cruise", "description": "The 4-hour cruise from Guilin to Yangshuo passes the most spectacular karst scenery in China.", "image_url": "/images/guilin/li_river.jpg"},
            {"name": "Reed Flute Cave", "description": "A magnificent limestone cave illuminated by colorful lights, filled with stunning stalactites.", "image_url": "/images/guilin/reed_cave.jpg"},
            {"name": "Elephant Trunk Hill", "description": "Guilin's iconic landmark — a hill shaped like an elephant drinking from the river.", "image_url": "/images/guilin/elephant_hill.jpg"},
        ],
        "must_eat": [
            {"name": "Guilin Rice Noodles", "description": "The city's signature dish — silky rice noodles in bone broth with pickled vegetables and chili.", "image_url": "/images/guilin/noodles.jpg"},
            {"name": "Beer Fish (Yangshuo)", "description": "Fresh river fish braised in beer with tomatoes and peppers — a Yangshuo specialty.", "image_url": "/images/guilin/beer_fish.jpg"},
            {"name": "Stuffed Li River Snails", "description": "River snails stuffed with minced pork and herbs, then steamed.", "image_url": "/images/guilin/snails.jpg"},
        ],
        "stay_tips": "Split your stay between Guilin city and Yangshuo county. Yangshuo is more charming for nature lovers, with cycling and hiking options.",
        "best_days": 4,
        "budget_range": "$$",
        "latitude": 25.2736,
        "longitude": 110.2900,
    },
    {
        "id": "hangzhou",
        "name": "Hangzhou",
        "name_cn": "杭州",
        "description": "The legendary city of West Lake — a literary and artistic muse for centuries, now a thriving tech hub.",
        "image_url": "/images/destinations/hangzhou.jpg",
        "tags": ["nature", "culture", "tea"],
        "must_see": [
            {"name": "West Lake", "description": "UNESCO World Heritage site with pagodas, temples, and gardens — best explored by boat or bicycle.", "image_url": "/images/hangzhou/west_lake.jpg"},
            {"name": "Lingyin Temple", "description": "One of China's most important Buddhist temples, surrounded by forested hills.", "image_url": "/images/hangzhou/lingyin.jpg"},
            {"name": "Longjing Tea Plantations", "description": "Visit the birthplace of Dragon Well tea, taste fresh tea, and see the terraced fields.", "image_url": "/images/hangzhou/longjing.jpg"},
        ],
        "must_eat": [
            {"name": "West Lake Vinegar Fish", "description": "Fresh fish from West Lake, steamed and dressed with a sweet-sour vinegar sauce.", "image_url": "/images/hangzhou/vinegar_fish.jpg"},
            {"name": "Dongpo Pork", "description": "Slow-braised pork belly named after the poet Su Dongpo — melt-in-your-mouth tender.", "image_url": "/images/hangzhou/dongpo_pork.jpg"},
            {"name": "Longjing Shrimp", "description": "River shrimp stir-fried with Longjing tea leaves — delicate and fragrant.", "image_url": "/images/hangzhou/tea_shrimp.jpg"},
        ],
        "stay_tips": "Stay near West Lake (Hubin area) for the best views and walking access. The city is well-connected by metro and high-speed rail.",
        "best_days": 2,
        "budget_range": "$$$",
        "latitude": 30.2741,
        "longitude": 120.1551,
    },
    {
        "id": "suzhou",
        "name": "Suzhou",
        "name_cn": "苏州",
        "description": "The Venice of the East — famous for its classical gardens, silk production, and historic water towns.",
        "image_url": "/images/destinations/suzhou.jpg",
        "tags": ["culture", "history", "gardens"],
        "must_see": [
            {"name": "Humble Administrator's Garden", "description": "The largest and most famous classical Chinese garden, a UNESCO site.", "image_url": "/images/suzhou/humble_admin.jpg"},
            {"name": "Pingjiang Road", "description": "A historic canal-side street with traditional architecture, teahouses, and boutiques.", "image_url": "/images/suzhou/pingjiang.jpg"},
            {"name": "Tongli Water Town", "description": "One of the best-preserved ancient water towns with canals, bridges, and Ming/Qing architecture.", "image_url": "/images/suzhou/tongli.jpg"},
        ],
        "must_eat": [
            {"name": "Squirrel-Shaped Mandarin Fish", "description": "A Suzhou classic — deep-fried fish in sweet-sour sauce, shaped to look like a squirrel.", "image_url": "/images/suzhou/squirrel_fish.jpg"},
            {"name": "Suzhou Noodles", "description": "Thin noodles in rich broth, typically served with various toppings like braised pork or shrimp.", "image_url": "/images/suzhou/noodles.jpg"},
            {"name": "Steamed Osmanthus Cake", "description": "A sweet rice cake flavored with osmanthus flowers — a delicate Suzhou treat.", "image_url": "/images/suzhou/cake.jpg"},
        ],
        "stay_tips": "Stay near Guanqian Street or Jinji Lake. Suzhou is a 30-min high-speed train from Shanghai — great for a day trip or weekend stay.",
        "best_days": 2,
        "budget_range": "$$",
        "latitude": 31.2990,
        "longitude": 120.5853,
    },
    {
        "id": "nanjing",
        "name": "Nanjing",
        "name_cn": "南京",
        "description": "One of China's Four Great Ancient Capitals, Nanjing offers a profound historical experience with a modern edge.",
        "image_url": "/images/destinations/nanjing.jpg",
        "tags": ["history", "culture", "nature"],
        "must_see": [
            {"name": "Sun Yat-sen Mausoleum", "description": "An impressive hillside memorial dedicated to the founding father of modern China.", "image_url": "/images/nanjing/sun_yatsen.jpg"},
            {"name": "Confucius Temple (Fuzimiao)", "description": "A lively temple complex on the Qinhuai River with markets, food stalls, and nightlife.", "image_url": "/images/nanjing/fuzimiao.jpg"},
            {"name": "Nanjing City Wall", "description": "The longest city wall in the world, stretching 35km around the old city.", "image_url": "/images/nanjing/city_wall.jpg"},
        ],
        "must_eat": [
            {"name": "Nanjing Salted Duck", "description": "The city's most famous dish — tender, flavorful duck cured and poached in brine.", "image_url": "/images/nanjing/salted_duck.jpg"},
            {"name": "Duck Blood Vermicelli Soup", "description": "A warming bowl of duck blood curd, tofu puffs, and vermicelli in rich duck broth.", "image_url": "/images/nanjing/duck_soup.jpg"},
            {"name": "Pan-fried Beef Dumplings", "description": "Juicy beef-filled dumplings with a crispy bottom, a local breakfast favorite.", "image_url": "/images/nanjing/beef_dumplings.jpg"},
        ],
        "stay_tips": "Xinjiekou area is the city center, well-connected and close to major attractions. The metro system is comprehensive.",
        "best_days": 2,
        "budget_range": "$$",
        "latitude": 32.0603,
        "longitude": 118.7969,
    },
    {
        "id": "lijiang",
        "name": "Lijiang",
        "name_cn": "丽江",
        "description": "A UNESCO World Heritage old town at the foot of snow-capped mountains, known for Naxi culture and stunning natural scenery.",
        "image_url": "/images/destinations/lijiang.jpg",
        "tags": ["culture", "nature", "history"],
        "must_see": [
            {"name": "Lijiang Old Town", "description": "A maze of cobblestone streets, canals, and Naxi architecture dating back 800 years.", "image_url": "/images/lijiang/old_town.jpg"},
            {"name": "Jade Dragon Snow Mountain", "description": "A majestic 5,596m peak with cable cars, hiking trails, and year-round snow.", "image_url": "/images/lijiang/jade_dragon.jpg"},
            {"name": "Tiger Leaping Gorge", "description": "One of the world's deepest gorges, offering spectacular hiking among 5,000m peaks.", "image_url": "/images/lijiang/tiger_gorge.jpg"},
        ],
        "must_eat": [
            {"name": "Naxi Grilled Fish", "description": "Local river fish grilled with spices and herbs, a Naxi traditional dish.", "image_url": "/images/lijiang/grilled_fish.jpg"},
            {"name": "Crossing-the-Bridge Noodles", "description": "Yunnan's famous noodle dish — boiling broth served with rice noodles and raw ingredients to cook at the table.", "image_url": "/images/lijiang/bridge_noodles.jpg"},
            {"name": "Yunnan Ham", "description": "Cured Yunnan ham, prized for its intense flavor similar to prosciutto.", "image_url": "/images/lijiang/ham.jpg"},
        ],
        "stay_tips": "Stay inside the Old Town for atmosphere (though it can be noisy). For quieter options, try Shuhe Ancient Town nearby. Book guesthouses in advance.",
        "best_days": 3,
        "budget_range": "$$",
        "latitude": 26.8721,
        "longitude": 100.2260,
    },
    {
        "id": "kunming",
        "name": "Kunming",
        "name_cn": "昆明",
        "description": "The Spring City — Kunming enjoys year-round mild weather and serves as the gateway to Yunnan's diverse attractions.",
        "image_url": "/images/destinations/kunming.jpg",
        "tags": ["nature", "culture", "gateway"],
        "must_see": [
            {"name": "Stone Forest (Shilin)", "description": "A surreal landscape of limestone karst formations that look like a petrified forest.", "image_url": "/images/kunming/stone_forest.jpg"},
            {"name": "Yuantong Temple", "description": "Kunming's most important Buddhist temple, elegantly designed around a central pond.", "image_url": "/images/kunming/yuantong.jpg"},
            {"name": "Dianchi Lake", "description": "The largest lake in Yunnan, with the majestic Western Hills as backdrop.", "image_url": "/images/kunming/dianchi.jpg"},
        ],
        "must_eat": [
            {"name": "Crossing-the-Bridge Noodles", "description": "Kunming's signature dish — the original 'guoqiao mixian' experience.", "image_url": "/images/kunming/bridge_noodles.jpg"},
            {"name": "Steam Pot Chicken", "description": "Chicken steamed in a special clay pot with medicinal herbs — clear, flavorful broth.", "image_url": "/images/kunming/steam_chicken.jpg"},
            {"name": "Yunnan Mushroom Hotpot", "description": "Wild mushroom hotpot featuring Yunnan's famous variety of edible fungi.", "image_url": "/images/kunming/mushroom_hotpot.jpg"},
        ],
        "stay_tips": "Stay near Jinma Biji Square or Green Lake Park. Kunming is the hub for exploring Dali, Lijiang, and Shangri-La.",
        "best_days": 2,
        "budget_range": "$$",
        "latitude": 25.0389,
        "longitude": 102.7183,
    },
    {
        "id": "zhangjiajie",
        "name": "Zhangjiajie",
        "name_cn": "张家界",
        "description": "The inspiration for the floating mountains in Avatar — impossibly tall quartzite sandstone pillars rising from the mist.",
        "image_url": "/images/destinations/zhangjiajie.jpg",
        "tags": ["nature", "adventure", "photography"],
        "must_see": [
            {"name": "Zhangjiajie National Forest Park", "description": "UNESCO site with thousands of towering sandstone pillars, including the famous 'Avatar Hallelujah Mountain'.", "image_url": "/images/zhangjiajie/national_park.jpg"},
            {"name": "Tianmen Mountain", "description": "The 'Heaven's Gate' mountain with the world's longest cable car ride and a glass skywalk.", "image_url": "/images/zhangjiajie/tianmen.jpg"},
            {"name": "Grand Canyon Glass Bridge", "description": "The world's longest and highest glass-bottomed bridge, 300m above the canyon floor.", "image_url": "/images/zhangjiajie/glass_bridge.jpg"},
        ],
        "must_eat": [
            {"name": "Tujia Three Staple Dishes", "description": "Three traditional Tujia dishes: bacon, tofu, and pickled vegetables.", "image_url": "/images/zhangjiajie/tujia.jpg"},
            {"name": "Zhangjiajie Tofu", "description": "Locally-made tofu in a spicy sauce with minced pork.", "image_url": "/images/zhangjiajie/tofu.jpg"},
            {"name": "Mountain Wild Vegetables", "description": "Seasonal wild foraged vegetables stir-fried with local seasonings.", "image_url": "/images/zhangjiajie/wild_veg.jpg"},
        ],
        "stay_tips": "Stay in Wulingyuan town near the park entrance. The park requires at least 2 full days. Book tickets online in advance.",
        "best_days": 3,
        "budget_range": "$$",
        "latitude": 29.3489,
        "longitude": 110.4779,
    },
    {
        "id": "hong_kong",
        "name": "Hong Kong",
        "name_cn": "香港",
        "description": "A dazzling Special Administrative Region where East meets West — towering skyline, world-class dining, and vibrant street culture.",
        "image_url": "/images/destinations/hong_kong.jpg",
        "tags": ["modern", "shopping", "food"],
        "must_see": [
            {"name": "Victoria Peak", "description": "Hong Kong's most iconic viewpoint — take the Peak Tram for breathtaking skyline views.", "image_url": "/images/hongkong/peak.jpg"},
            {"name": "Tsim Sha Tsui Promenade", "description": "Stroll along the harbour with stunning views of the Hong Kong Island skyline.", "image_url": "/images/hongkong/tst.jpg"},
            {"name": "Temple Street Night Market", "description": "A lively night market with street food, fortune tellers, and bargain shopping.", "image_url": "/images/hongkong/temple_street.jpg"},
        ],
        "must_eat": [
            {"name": "Dim Sum", "description": "Hong Kong's dim sum culture is legendary — from Michelin-starred to hole-in-the-wall.", "image_url": "/images/hongkong/dimsum.jpg"},
            {"name": "Egg Waffles (Eggettes)", "description": "Crispy, eggy bubble waffles — the quintessential Hong Kong street snack.", "image_url": "/images/hongkong/egg_waffles.jpg"},
            {"name": "Roast Goose", "description": "Crispy-skinned roast goose, especially from legendary restaurants like Yat Lok.", "image_url": "/images/hongkong/roast_goose.jpg"},
        ],
        "stay_tips": "Tsim Sha Tsui (Kowloon side) offers the best skyline views. Central and Causeway Bay (Hong Kong Island) are for luxury shopping. The MTR is world-class.",
        "best_days": 3,
        "budget_range": "$$$$",
        "latitude": 22.3193,
        "longitude": 114.1694,
    },
    {
        "id": "harbin",
        "name": "Harbin",
        "name_cn": "哈尔滨",
        "description": "China's Ice City — famous for its spectacular winter Ice and Snow Festival and Russian-influenced architecture.",
        "image_url": "/images/destinations/harbin.jpg",
        "tags": ["winter", "culture", "food"],
        "must_see": [
            {"name": "Ice and Snow World", "description": "A magical frozen kingdom of massive ice sculptures, illuminated with colorful lights.", "image_url": "/images/harbin/ice_world.jpg"},
            {"name": "Saint Sophia Cathedral", "description": "A stunning Byzantine-style Russian Orthodox cathedral, now a museum.", "image_url": "/images/harbin/sophia.jpg"},
            {"name": "Zhongyang Street", "description": "Harbin's historic pedestrian street lined with European architecture and shops.", "image_url": "/images/harbin/zhongyang.jpg"},
        ],
        "must_eat": [
            {"name": "Harbin Sausage", "description": "Smoked pork sausage with European influences — a Harbin institution.", "image_url": "/images/harbin/sausage.jpg"},
            {"name": "Russian Borscht", "description": "Hearty beetroot soup adapted to local tastes, served in many Harbin restaurants.", "image_url": "/images/harbin/borscht.jpg"},
            {"name": "Guo Bao Rou (Sweet and Sour Pork)", "description": "Crispy deep-fried pork in a translucent sweet-sour sauce — a Harbin specialty.", "image_url": "/images/harbin/guobaorou.jpg"},
        ],
        "stay_tips": "Visit in winter (Dec-Feb) for the Ice Festival. Stay near Zhongyang Street for the best atmosphere. Dress extremely warmly — temperatures can reach -30°C.",
        "best_days": 2,
        "budget_range": "$$",
        "latitude": 45.8038,
        "longitude": 126.5350,
    },
    {
        "id": "xiamen",
        "name": "Xiamen",
        "name_cn": "厦门",
        "description": "A charming coastal city with colonial architecture, pristine beaches, and a laid-back island vibe.",
        "image_url": "/images/destinations/xiamen.jpg",
        "tags": ["beach", "culture", "food"],
        "must_see": [
            {"name": "Gulangyu Island", "description": "A car-free island with colonial villas, piano museums, and stunning sea views.", "image_url": "/images/xiamen/gulangyu.jpg"},
            {"name": "Nanputuo Temple", "description": "A famous Buddhist temple at the foot of Wulao Mountain, with beautiful gardens.", "image_url": "/images/xiamen/nanputuo.jpg"},
            {"name": "Zhongshan Road", "description": "A pedestrian street with arcaded buildings, shops, and local street food.", "image_url": "/images/xiamen/zhongshan.jpg"},
        ],
        "must_eat": [
            {"name": "Oyster Omelette", "description": "Fresh oysters fried with egg and sweet potato starch, served with chili sauce.", "image_url": "/images/xiamen/oyster_omelette.jpg"},
            {"name": "Sha Cha Noodles", "description": "Noodles in a rich, savory satay sauce with pork, shrimp, and vegetables.", "image_url": "/images/xiamen/shacha_noodles.jpg"},
            {"name": "Taro Balls", "description": "Sweet and chewy taro-flavored balls, a popular Xiamen dessert.", "image_url": "/images/xiamen/taro_balls.jpg"},
        ],
        "stay_tips": "Stay near Zhongshan Road or Zengcuoan village for seaside atmosphere. Cross the bridge to Gulangyu for a unique island experience.",
        "best_days": 2,
        "budget_range": "$$",
        "latitude": 24.4798,
        "longitude": 118.0894,
    },
    {
        "id": "lhasa",
        "name": "Lhasa",
        "name_cn": "拉萨",
        "description": "The spiritual heart of Tibet — a breathtaking high-altitude city of monasteries, prayer flags, and the iconic Potala Palace.",
        "image_url": "/images/destinations/lhasa.jpg",
        "tags": ["culture", "religion", "adventure"],
        "must_see": [
            {"name": "Potala Palace", "description": "The iconic 13-story palace atop Red Hill, former winter residence of the Dalai Lama.", "image_url": "/images/lhasa/potala.jpg"},
            {"name": "Jokhang Temple", "description": "Tibet's most sacred Buddhist temple, drawing pilgrims from across the Tibetan Plateau.", "image_url": "/images/lhasa/jokhang.jpg"},
            {"name": "Barkhor Street", "description": "The pilgrim circuit around Jokhang Temple, lined with shops selling Tibetan crafts.", "image_url": "/images/lhasa/barkhor.jpg"},
        ],
        "must_eat": [
            {"name": "Tsampa", "description": "Roasted barley flour — a Tibetan staple, served with yak butter tea.", "image_url": "/images/lhasa/tsampa.jpg"},
            {"name": "Yak Butter Tea", "description": "A salty, buttery tea that provides energy in the high-altitude environment.", "image_url": "/images/lhasa/butter_tea.jpg"},
            {"name": "Momos (Tibetan Dumplings)", "description": "Steamed or fried dumplings filled with yak meat or vegetables.", "image_url": "/images/lhasa/momos.jpg"},
        ],
        "stay_tips": "Acclimate for 1-2 days before intensive sightseeing (altitude 3,650m). Foreign travelers need a Tibet Travel Permit. Avoid visiting during Tibetan New Year (stores may close).",
        "best_days": 4,
        "budget_range": "$$$",
        "latitude": 29.6500,
        "longitude": 91.1000,
    },
    {
        "id": "dunhuang",
        "name": "Dunhuang",
        "name_cn": "敦煌",
        "description": "An ancient Silk Road oasis town famous for its stunning Mogao Caves and surreal desert landscapes.",
        "image_url": "/images/destinations/dunhuang.jpg",
        "tags": ["history", "culture", "nature"],
        "must_see": [
            {"name": "Mogao Caves", "description": "A UNESCO site with 492 temple caves adorned with exquisite Buddhist murals and sculptures spanning 1,000 years.", "image_url": "/images/dunhuang/mogao.jpg"},
            {"name": "Singing Sand Dunes (Mingshashan)", "description": "Towering sand dunes that 'sing' when the wind blows, with a crescent-shaped oasis lake.", "image_url": "/images/dunhuang/sand_dunes.jpg"},
            {"name": "Crescent Moon Spring", "description": "A spring in the shape of a crescent moon, surrounded by sand dunes — an oasis miracle.", "image_url": "/images/dunhuang/crescent_spring.jpg"},
        ],
        "must_eat": [
            {"name": "Lanzhou Beef Noodles", "description": "Hand-pulled noodles in clear beef broth — a Silk Road classic.", "image_url": "/images/dunhuang/beef_noodles.jpg"},
            {"name": "Dunhuang Roast Lamb", "description": "Slow-roasted lamb with cumin and chili, reflecting Silk Road culinary influences.", "image_url": "/images/dunhuang/roast_lamb.jpg"},
            {"name": "Apricot Peel Water", "description": "A refreshing local drink made from dried Lanzhou apricots.", "image_url": "/images/dunhuang/apricot_drink.jpg"},
        ],
        "stay_tips": "Visit in spring or autumn to avoid extreme temperatures. The Mogao Caves require advance booking. Camel rides at the sand dunes are a must.",
        "best_days": 2,
        "budget_range": "$$",
        "latitude": 40.1421,
        "longitude": 94.6620,
    },
    {
        "id": "chengde",
        "name": "Chengde",
        "name_cn": "承德",
        "description": "A mountain retreat of Qing emperors, featuring China's largest imperial garden complex and stunning Tibetan-style temples.",
        "image_url": "/images/destinations/chengde.jpg",
        "tags": ["history", "culture", "nature"],
        "must_see": [
            {"name": "Mountain Resort (Bishu Shanzhuang)", "description": "The largest imperial garden in China, a UNESCO site combining lakes, plains, and mountain scenery.", "image_url": "/images/chengde/mountain_resort.jpg"},
            {"name": "Putuo Zongcheng Temple", "description": "A magnificent Tibetan-style temple modeled after the Potala Palace in Lhasa.", "image_url": "/images/chengde/putuo_temple.jpg"},
            {"name": "Puning Temple", "description": "Home to a 22m-tall wooden statue of the Thousand-Armed Guanyin.", "image_url": "/images/chengde/puning.jpg"},
        ],
        "must_eat": [
            {"name": "Chengde Wild Mushrooms", "description": "Foraged mountain mushrooms prepared in various styles.", "image_url": "/images/chengde/mushrooms.jpg"},
            {"name": "Qing Dynasty Imperial Dishes", "description": "Recreations of Qing imperial court cuisine.", "image_url": "/images/chengde/imperial_cuisine.jpg"},
            {"name": "Lamb Hotpot", "description": "Northern-style lamb hotpot — warming and satisfying.", "image_url": "/images/chengde/lamb_hotpot.jpg"},
        ],
        "stay_tips": "Chengde is 2 hours by train from Beijing — great for a weekend trip. Stay near the Mountain Resort for easy access.",
        "best_days": 2,
        "budget_range": "$$",
        "latitude": 40.9519,
        "longitude": 117.9581,
    },
    {
        "id": "jiuzhaigou",
        "name": "Jiuzhaigou",
        "name_cn": "九寨沟",
        "description": "A fairy-tale valley of turquoise lakes, multi-tiered waterfalls, and snow-capped peaks — one of China's most beautiful natural wonders.",
        "image_url": "/images/destinations/jiuzhaigou.jpg",
        "tags": ["nature", "photography", "hiking"],
        "must_see": [
            {"name": "Five Flower Lake", "description": "A shallow, stunningly clear lake with submerged tree trunks visible in turquoise water.", "image_url": "/images/jiuzhaigou/five_flower.jpg"},
            {"name": "Nuorilang Waterfall", "description": "China's widest waterfall, cascading 320m across a terraced cliff.", "image_url": "/images/jiuzhaigou/nuorilang.jpg"},
            {"name": "Long Lake", "description": "The largest lake in Jiuzhaigou, reflecting the surrounding mountains in its deep blue surface.", "image_url": "/images/jiuzhaigou/long_lake.jpg"},
        ],
        "must_eat": [
            {"name": "Tibetan Yak Yogurt", "description": "Rich, tangy yogurt made from local yak milk.", "image_url": "/images/jiuzhaigou/yak_yogurt.jpg"},
            {"name": "Highland Barley Wine", "description": "A mild, sweet fermented barley drink — the local 'beer' of the Tibetan Plateau.", "image_url": "/images/jiuzhaigou/barley_wine.jpg"},
            {"name": "Roasted Yak Meat", "description": "Simple but flavorful — local yak meat seasoned with salt and chili.", "image_url": "/images/jiuzhaigou/roasted_yak.jpg"},
        ],
        "stay_tips": "Book park entrance tickets online well in advance (limited daily capacity). Visit in autumn (Oct-Nov) for the most spectacular fall colors. The park requires a full day.",
        "best_days": 2,
        "budget_range": "$$$",
        "latitude": 33.2621,
        "longitude": 103.9233,
    },
    {
        "id": "qingdao",
        "name": "Qingdao",
        "name_cn": "青岛",
        "description": "A coastal city with German colonial architecture, world-famous Tsingtao beer, and beautiful beaches.",
        "image_url": "/images/destinations/qingdao.jpg",
        "tags": ["beach", "food", "culture"],
        "must_see": [
            {"name": "Zhanqiao Pier", "description": "Qingdao's iconic landmark — a long pier extending into the sea with a traditional Chinese pavilion.", "image_url": "/images/qingdao/zhanqiao.jpg"},
            {"name": "Tsingtao Beer Museum", "description": "Housed in the original German-built brewery, tracing the history of China's most famous beer.", "image_url": "/images/qingdao/beer_museum.jpg"},
            {"name": "Badaguan Scenic Area", "description": "Quaint tree-lined streets with a charming collection of European-style villas.", "image_url": "/images/qingdao/badaguan.jpg"},
        ],
        "must_eat": [
            {"name": "Seafood (clams, prawns, squid)", "description": "Fresh seafood from the Yellow Sea — simply steamed or grilled at beachfront stalls.", "image_url": "/images/qingdao/seafood.jpg"},
            {"name": "Tsingtao Beer", "description": "Enjoy a fresh pint at the Beer Museum or one of the city's many beer bars.", "image_url": "/images/qingdao/tsingtao_beer.jpg"},
            {"name": "Qingdao-style Clams", "description": "Local clams stir-fried with garlic and chili — the perfect beer snack.", "image_url": "/images/qingdao/clams.jpg"},
        ],
        "stay_tips": "Visit in summer (June-August) for beach weather. Stay near the Old Town (Shinan district) for proximity to main attractions and the waterfront.",
        "best_days": 2,
        "budget_range": "$$",
        "latitude": 36.0671,
        "longitude": 120.3826,
    },
    {
        "id": "dali",
        "name": "Dali",
        "name_cn": "大理",
        "description": "A laid-back ancient town nestled between Erhai Lake and the Cangshan Mountains — a haven for artists, writers, and wanderers.",
        "image_url": "/images/destinations/dali.jpg",
        "tags": ["nature", "culture", "relaxation"],
        "must_see": [
            {"name": "Erhai Lake", "description": "A breathtaking lake surrounded by mountains — cycle the shoreline or take a boat cruise.", "image_url": "/images/dali/erhai.jpg"},
            {"name": "Dali Old Town", "description": "A well-preserved ancient town with cobblestone streets, traditional Bai architecture, and a relaxed vibe.", "image_url": "/images/dali/old_town.jpg"},
            {"name": "Three Pagodas", "description": "Dali's iconic landmark — three pagodas standing for over 1,000 years against the Cangshan backdrop.", "image_url": "/images/dali/three_pagodas.jpg"},
        ],
        "must_eat": [
            {"name": "Crossing-the-Bridge Noodles", "description": "Yunnan's famous noodle soup, done beautifully in Dali.", "image_url": "/images/dali/bridge_noodles.jpg"},
            {"name": "Bai-style Fish", "description": "Fresh fish from Erhai Lake, steamed with local herbs and spices.", "image_url": "/images/dali/bai_fish.jpg"},
            {"name": "Rushan (Milk Fan)", "description": "A unique Bai cheese made from cow's milk, grilled or fried and served with sugar or chili.", "image_url": "/images/dali/rushan.jpg"},
        ],
        "stay_tips": "Stay in Dali Old Town for atmosphere, or by Erhai Lake for tranquility. Rent an e-bike to explore the lake shoreline. Spring and autumn are ideal.",
        "best_days": 3,
        "budget_range": "$",
        "latitude": 25.6866,
        "longitude": 100.1575,
    },
    {
        "id": "macau",
        "name": "Macau",
        "name_cn": "澳门",
        "description": "The Las Vegas of Asia — a former Portuguese colony offering a unique blend of European heritage, glitzy casinos, and Michelin-starred dining.",
        "image_url": "/images/destinations/macau.jpg",
        "tags": ["shopping", "food", "culture"],
        "must_see": [
            {"name": "Ruins of St. Paul's", "description": "Macau's most iconic landmark — the baroque facade of a 17th-century Jesuit church.", "image_url": "/images/macau/st_pauls.jpg"},
            {"name": "Macau Tower", "description": "A 338m tower with panoramic views and the world's highest commercial bungee jump.", "image_url": "/images/macau/tower.jpg"},
            {"name": "Senado Square", "description": "A charming Portuguese-style square with wave-patterned cobblestones and pastel buildings.", "image_url": "/images/macau/senado.jpg"},
        ],
        "must_eat": [
            {"name": "Portuguese Egg Tarts", "description": "Macau's most famous export — flaky, buttery pastry with silky egg custard.", "image_url": "/images/macau/egg_tarts.jpg"},
            {"name": "Portuguese-style Seafood Rice", "description": "A rich rice dish loaded with seafood in a saffron-infused broth.", "image_url": "/images/macau/seafood_rice.jpg"},
            {"name": "Pork Chop Bun", "description": "A simple but legendary Macau street food — crispy pork chop in a soft bun.", "image_url": "/images/macau/pork_chop_bun.jpg"},
        ],
        "stay_tips": "Macau is a 1-hour ferry from Hong Kong. Stay on the Macau Peninsula for history and culture, or Taipa/Cotai for casinos and luxury resorts.",
        "best_days": 2,
        "budget_range": "$$$",
        "latitude": 22.1987,
        "longitude": 113.5439,
    },
    {
        "id": "taipei",
        "name": "Taipei",
        "name_cn": "台北",
        "description": "A vibrant metropolis where traditional Chinese culture meets modern urban life, famous for night markets, tea culture, and friendly locals.",
        "image_url": "/images/destinations/taipei.jpg",
        "tags": ["food", "culture", "shopping"],
        "must_see": [
            {"name": "Taipei 101", "description": "One of the world's tallest skyscrapers, with a stunning observatory and the iconic damper sphere.", "image_url": "/images/taipei/taipei101.jpg"},
            {"name": "National Palace Museum", "description": "Home to the world's largest collection of Chinese imperial artifacts and artworks.", "image_url": "/images/taipei/palace_museum.jpg"},
            {"name": "Chiang Kai-shek Memorial Hall", "description": "An impressive monument and cultural complex within Liberty Square.", "image_url": "/images/taipei/ck_memorial.jpg"},
        ],
        "must_eat": [
            {"name": "Beef Noodle Soup", "description": "Taipei's signature dish — tender braised beef in rich broth with hand-pulled noodles.", "image_url": "/images/taipei/beef_noodles.jpg"},
            {"name": "Xiaolongbao (Soup Dumplings)", "description": "Din Tai Fung, the world-famous soup dumpling chain, originated in Taipei.", "image_url": "/images/taipei/xiaolongbao.jpg"},
            {"name": "Stinky Tofu", "description": "An acquired taste but a must-try — deep-fermented tofu, fried to golden perfection.", "image_url": "/images/taipei/stinky_tofu.jpg"},
        ],
        "stay_tips": "Ximending and Da'an district are the best bases for visitors. The MRT is clean, efficient, and English-friendly. Night markets (Shilin, Raohe) are unmissable.",
        "best_days": 4,
        "budget_range": "$$",
        "latitude": 25.0330,
        "longitude": 121.5654,
    },
    {
        "id": "wuhan",
        "name": "Wuhan",
        "name_cn": "武汉",
        "description": "A major transportation hub on the Yangtze River, known for its hearty food, university energy, and spring cherry blossoms.",
        "image_url": "/images/destinations/wuhan.jpg",
        "tags": ["food", "culture", "history"],
        "must_see": [
            {"name": "Yellow Crane Tower", "description": "An iconic Tang Dynasty tower with stunning views of the Yangtze River.", "image_url": "/images/wuhan/yellow_crane.jpg"},
            {"name": "East Lake", "description": "China's largest urban lake — three times the size of West Lake in Hangzhou.", "image_url": "/images/wuhan/east_lake.jpg"},
            {"name": "Hubei Provincial Museum", "description": "Famous for its ancient bronze chime bells and the Sword of Goujian.", "image_url": "/images/wuhan/hubei_museum.jpg"},
        ],
        "must_eat": [
            {"name": "Regan Noodles", "description": "Wuhan's signature breakfast — dry sesame noodles with pickled vegetables and chili.", "image_url": "/images/wuhan/regan.jpg"},
            {"name": "Wuhan Hot Dry Noodles", "description": "Another famous noodle dish — tossed in sesame paste, soy sauce, and scallions.", "image_url": "/images/wuhan/hot_dry_noodles.jpg"},
            {"name": "Wuchang Fish", "description": "A local freshwater fish, typically steamed with ginger and scallions.", "image_url": "/images/wuhan/wuchang_fish.jpg"},
        ],
        "stay_tips": "Stay near Wuchang or Hankou districts. Wuchang is near Yellow Crane Tower and East Lake; Hankou has better nightlife and food streets.",
        "best_days": 2,
        "budget_range": "$",
        "latitude": 30.5928,
        "longitude": 114.3055,
    },
]
